// <auto-generated />
namespace TrackApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingautogenerateoptiontotheprimarykeyofLocationDatatable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingautogenerateoptiontotheprimarykeyofLocationDatatable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705230946106_Adding auto generate option to the primary key of LocationData table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
