// <auto-generated />
namespace TrackApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingaconstructortoautogenerateGuidintheLocationDataobject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingaconstructortoautogenerateGuidintheLocationDataobject));
        
        string IMigrationMetadata.Id
        {
            get { return "201705230953016_Adding a constructor to auto generate Guid in the LocationData object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
